In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.1


In [3]:
print(np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

In [62]:
a = np.random.randint(1, 10,size=(2,3,5))
a

array([[[3, 4, 2, 6, 4],
        [6, 5, 9, 8, 2],
        [6, 4, 8, 4, 1]],

       [[8, 9, 5, 5, 8],
        [4, 5, 6, 2, 7],
        [9, 2, 6, 8, 2]]])

In [55]:
a_2 = np.random.rand(2,3,5)
a_2

array([[[0.00445535, 0.5751054 , 0.12350929, 0.2069544 , 0.89556846],
        [0.92464455, 0.16905037, 0.08949467, 0.53487219, 0.40075328],
        [0.44247765, 0.53697854, 0.38154561, 0.99599321, 0.83078623]],

       [[0.63774424, 0.41371545, 0.80785445, 0.18443401, 0.63079263],
        [0.01414083, 0.27860683, 0.1782011 , 0.69694423, 0.73956154],
        [0.40087597, 0.80900933, 0.85980301, 0.28240201, 0.10692025]]])

In [70]:
b_2 = np.random.randint(1,2, size=(5,2,3))
b_2

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [71]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
def numpy_info(array_name):
    print(f"size is {array_name.size}")
    print(f"shape is {array_name.shape}")
    print(f"dimension is {array_name.ndim}")

In [73]:
numpy_info(a)

size is 30
shape is (2, 3, 5)
dimension is 3


In [74]:
numpy_info(b)

size is 30
shape is (5, 2, 3)
dimension is 3


In [79]:
def compare(a,b):
    if a.shape == b.shape:
        print(f"they are the same shape:{a.shape}")
    elif a.shape != b.shape:
        print(f"NOPE a is {a.shape} and b is {b.shape}")
compare(a,b)

NOPE a is (2, 3, 5) and b is (5, 2, 3)


In [76]:
result = a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [98]:
# from (5,2,3) to (2,3,5)
# index 1 goes to index 0
# index 2 goes to index 1
# index 0 goes to index 2
c = b.transpose((1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [100]:
print(c.shape)
print(a.shape)

(2, 3, 5)
(2, 3, 5)


In [102]:
c.shape == a.shape

True

In [104]:
d = a + c
d

array([[[ 4.,  5.,  3.,  7.,  5.],
        [ 7.,  6., 10.,  9.,  3.],
        [ 7.,  5.,  9.,  5.,  2.]],

       [[ 9., 10.,  6.,  6.,  9.],
        [ 5.,  6.,  7.,  3.,  8.],
        [10.,  3.,  7.,  9.,  3.]]])

In [105]:
print(a)
print(d)

[[[3 4 2 6 4]
  [6 5 9 8 2]
  [6 4 8 4 1]]

 [[8 9 5 5 8]
  [4 5 6 2 7]
  [9 2 6 8 2]]]
[[[ 4.  5.  3.  7.  5.]
  [ 7.  6. 10.  9.  3.]
  [ 7.  5.  9.  5.  2.]]

 [[ 9. 10.  6.  6.  9.]
  [ 5.  6.  7.  3.  8.]
  [10.  3.  7.  9.  3.]]]


In [107]:
e = a * c
e

array([[[3., 4., 2., 6., 4.],
        [6., 5., 9., 8., 2.],
        [6., 4., 8., 4., 1.]],

       [[8., 9., 5., 5., 8.],
        [4., 5., 6., 2., 7.],
        [9., 2., 6., 8., 2.]]])

In [108]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [115]:
np.array_equal(a,e)

True

In [116]:
d_max = np.max(d)
d_max

10.0

In [118]:
d_min = np.min(d)
d_min

2.0

In [120]:
d_mean = np.mean(d)
d_mean

6.266666666666667

In [123]:
f = np.empty((2,3,5))
f

array([[[3., 4., 2., 6., 4.],
        [6., 5., 9., 8., 2.],
        [6., 4., 8., 4., 1.]],

       [[8., 9., 5., 5., 8.],
        [4., 5., 6., 2., 7.],
        [9., 2., 6., 8., 2.]]])

In [128]:
# for i in d 

# if d_min < d < d_mean, 25

# if  d_mean < d < d_max, 75

# if d == d_mean, 50

# if d == d_min, 0

#if d == d_max, 100
    

SyntaxError: incomplete input (1230754036.py, line 14)

In [129]:
f.shape == d.shape

True

In [153]:
print(d)

[[[ 4.  5.  3.  7.  5.]
  [ 7.  6. 10.  9.  3.]
  [ 7.  5.  9.  5.  2.]]

 [[ 9. 10.  6.  6.  9.]
  [ 5.  6.  7.  3.  8.]
  [10.  3.  7.  9.  3.]]]


In [149]:
print(d[0])

[[ 4.  5.  3.  7.  5.]
 [ 7.  6. 10.  9.  3.]
 [ 7.  5.  9.  5.  2.]]


In [150]:
print(d[0][0])

[4. 5. 3. 7. 5.]


In [156]:
print(d[0][0][0])

4.0


In [168]:
print(range(f.shape[0]))
print(range(f.shape[1]))
print(range(f.shape[2]))

range(0, 2)
range(0, 3)
range(0, 5)


In [170]:
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if d[i, j ,k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
                
                
                 

In [171]:
print(f)
print(f.shape[2])

[[[ 25.  25.  25.  75.  25.]
  [ 75.  25. 100.  75.  25.]
  [ 75.  25.  75.  25.   0.]]

 [[ 75. 100.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [100.  25.  75.  75.  25.]]]
5


In [172]:
f = np.empty((2,3,5), dtype=str)

for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if d[i, j ,k] == d_min:
                f[i, j, k] = "A"
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = "D"
            elif d[i, j, k] == d_max:
                f[i, j, k] = "E"
                

In [173]:
print(f)

[[['B' 'B' 'B' 'D' 'B']
  ['D' 'B' 'E' 'D' 'B']
  ['D' 'B' 'D' 'B' 'A']]

 [['D' 'E' 'B' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['E' 'B' 'D' 'D' 'B']]]
