In [85]:
#1. Import the NUMPY package under the name np. 
import numpy as np

In [86]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.24.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [197]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
import random
a = np.random.randint(100, size=(2,3,5))
a2 = np.random.random(size=(2,3,5))
a3 = np.random.rand(2,3,5)

In [196]:
#4. Print a.
print(a)
print(a2)
print(a3)


[[[94 17 84  7 93]
  [81 10 98 51 90]
  [24 67 88 28 33]]

 [[94 63 54 40 36]
  [84 55 89 22 14]
  [98 27 73 11 91]]]
[[[0.35177952 0.71899883 0.09736578 0.09258013 0.71778154]
  [0.17095881 0.23189631 0.66863216 0.38810352 0.35771047]
  [0.35651939 0.68958414 0.75252914 0.74135556 0.23200335]]

 [[0.02577543 0.0949961  0.39108281 0.58670087 0.77945602]
  [0.06676111 0.50163925 0.22561454 0.29298408 0.26325334]
  [0.49340027 0.29891684 0.11260572 0.76899449 0.25856427]]]
[[[0.32804885 0.92283734 0.10242717 0.31657006 0.71204465]
  [0.40182758 0.02497126 0.12370583 0.20186403 0.49963263]
  [0.32319229 0.67527684 0.37685219 0.37883875 0.49240909]]

 [[0.81048623 0.74674574 0.44093917 0.08373785 0.50799404]
  [0.03108786 0.14065117 0.51486839 0.69421243 0.94593595]
  [0.88444423 0.12108158 0.8824814  0.69392928 0.3545146 ]]]


In [111]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))


In [112]:
#6. Print b.
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [113]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [114]:
#8. Are you able to add a and b? Why or why not?
print(a + b)
# We cannot add a and b because the shape of each array is different 
# -> we should transpose one of them to match with the other and be able to operate with 
# both of them.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [115]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose(1,2,0)

In [116]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
# Now it works because both arrays have the very same size: 2x3x5 

In [117]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[ 0 95 74 75 24]
  [95 39 20 49 63]
  [80 40  0  8 41]]

 [[53 96 54 17 84]
  [81 40 22 47 30]
  [49 76 51 68 59]]]
[[[ 1. 96. 75. 76. 25.]
  [96. 40. 21. 50. 64.]
  [81. 41.  1.  9. 42.]]

 [[54. 97. 55. 18. 85.]
  [82. 41. 23. 48. 31.]
  [50. 77. 52. 69. 60.]]]


In [118]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [119]:
#13. Does e equal to a? Why or why not?
print(e == a)

if e.all() == a.all():
    print("e equals a")
else:
    print("e is not the same as a")

# All elements are the same since all a's are multiplied by one.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
e equals a


In [120]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

97.0
1.0
52.0


In [121]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty(shape=(2,3,5), dtype=object)

In [183]:

# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
print(d)
d[0][0][0]

[[[ 1. 96. 75. 76. 25.]
  [96. 40. 21. 50. 64.]
  [81. 41.  1.  9. 42.]]

 [[54. 97. 55. 18. 85.]
  [82. 41. 23. 48. 31.]
  [50. 77. 52. 69. 60.]]]


1.0

In [188]:
for dimension in range(d.shape[0]):
    for row in range(d.shape[1]):
        for element in range(d.shape[2]):

            if d[dimension][row][element] == d_min:
                f[dimension][row][element] = 0
            elif d[dimension][row][element] == d_max:
                f[dimension][row][element] = 100
            elif d[dimension][row][element] == d_mean:
                f[dimension][row][element] = 50
            elif d[dimension][row][element] > d_mean and d[dimension][row][element] < d_max:
                f[dimension][row][element] = 75
            elif d[dimension][row][element] > d_min and d[dimension][row][element] < d_mean:
                f[dimension][row][element] = 25

In [190]:

# 17. Print d and f. Do you have your expected f?
# For instance, if your d is:
# array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
#        [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Your f should be:
# array([[[ 75.,  75.,  75.,  25.,  75.],
#        [ 75.,  75.,  25.,  25.,  25.],
#        [ 75.,  25.,  75.,  75.,  75.]],
#
#       [[ 25.,  25.,  25.,  25., 100.],
#        [ 75.,  75.,  75.,  75.,  75.],
#        [ 25.,  75.,   0.,  75.,  75.]]])


In [191]:
f

array([[[0, 75, 75, 75, 25],
        [75, 25, 25, 25, 75],
        [75, 25, 0, 25, 25]],

       [[75, 100, 75, 25, 75],
        [75, 25, 25, 25, 25],
        [25, 75, 50, 75, 75]]], dtype=object)

In [102]:

# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.